### ISSUE TITLE
Add changelog/release notes for this project

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lib#39]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'd like to check release notes with the changes made for each version. 

**Describe the solution you'd like**
Add SDK changelog solution and release notes in MD doc.

**Comment by varshaprasad96** [comment]
Currently, since there are not many changes between each versions (and no release binaries), the release process is quick and we are drafting the release notes by hand. But with the increase in visibility and contributions to operator-lib, I completely agree that we could have a more defined process as in SDK (with changelog fragments).
