### ISSUE TITLE
How to properly import the library

### ISSUE THREAD

**Issue by Dhvani3IBM** [operator-framework/operator-lib#63]
## Type of question

Importing and using operator-lib

## Question

**What did you do?**
I ran `go get github.com/operator-framework/operator-lib`, and added the following to my main.go operator code:
`import (
olib "github.com/operator-framework/operator-lib"
)
`

`olib.GetOperatorNamespace()`

**What did you expect to see?**
`go mod tidy` succeeding.

**What did you see instead? Under which circumstances?**
go: finding module for package github.com/operator-framework/operator-lib
XXXXXXXXXX imports
	github.com/operator-framework/operator-lib: module github.com/operator-framework/operator-lib@latest found (v0.4.1), but does not contain package github.com/operator-framework/operator-lib

**Environment**
* operator-lib version: 0.4.1
Mac OS

**Comment by Dhvani3IBM** [comment]
Yes you are right, I fixed my import to:

`github.com/operator-framework/operator-lib/internal/utils`

but ahh its internal. Why is it not public? Is it not recommended to use for getting the namespace the operator is installed in?

**Comment by joelanford** [comment]
There's been some back-and-forth in that past about this particular featre because it only works when running inside a cluster, and everyone has different opinions about how it should work when running outside of a cluster. 
- Should it return an error? 
- Should it allow the namespace lookup mechanism to be overridden? 
- Should it first check an environment variable before checking the service account-mounted namespace file?

In the end, its a very personal decision related to your particular use case and since its completely trivial (i.e. read the contents of a specific file), my guess is that we decided to just stay out of the fray. Otherwise we'd risk making this way more complicated than just about everybody needs.

**Comment by Dhvani3IBM** [comment]
Ahh okay. So if I am running this inside of a cluster, then that file is reading is expected to be there, and so its okay if I just copy over the code? 

If that's the case, then I'll just do that then and close the issue.

Thanks for the quick replies, I appreciate it!

**Comment by joelanford** [comment]
> So if I am running this inside of a cluster, then that file is reading is expected to be there, and so its okay if I just copy over the code? 

Yep!

**Comment by Dhvani3IBM** [comment]
Sweet, thanks!
